<?php 
	$a = 100;
	echo($a."<br>");
	$b = &$a;
	$b+=10;
	echo($a);
 ?>

 <?php
 $arr= array("SERVER_SOFTWARE"=>"SERVER_SOFTWARE","SERVER_NAME"=>"SERVER_NAME","GATEWAY_INTERFACE"=>"GATEWAY_INTERFACE","SERVER_PROTOCOL"=>"SERVER_PROTOCOL","SERVER_PORT"=>"SERVER_PORT","REQUEST_METHOD"=>"REQUEST_METHOD","SCRIPT_NAME"=>"SCRIPT_NAME","QUERY_STRING"=>"QUERY_STRING","REMOTE_HOST"=>"REMOTE_HOST","REMOTE_ADDR"=>"REMOTE_ADDR","CONTENT_TYPE"=>"CONTENT_TYPE","CONTENT_LENGTH"=>"CONTENT_LENGTH","HTTP_ACCEPT"=>"HTTP_ACCEPT","HTTP_USER_AGENT"=>"HTTP_USER_AGENT");
 foreach ($arr as $k=>$elem)  {  echo $k,":  ",getenv($elem),"<br>";} 
 ?>
